### ISSUE TITLE
[error] GenServer :tzdata_release_updater terminating

### ISSUE THREAD

**Issue by adrianotadao** [smeevil/cloudex#22]
Hello, I'm receiving this error and I don't know why.

```
[info] Running LinkService.Endpoint with Cowboy using http://localhost:4000
Interactive Elixir (1.4.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 08 Mar 16:05:55 - info: compiled 6 files into 2 files, copied 3 in 1.6 sec
[debug] Tzdata polling for update.
[error] GenServer :tzdata_release_updater terminating
** (ArgumentError) argument error
    :erlang.hd([])
    (tzdata) lib/tzdata/data_loader.ex:29: Tzdata.DataLoader.content_length_from_headers/1
    (tzdata) lib/tzdata/data_loader.ex:51: Tzdata.DataLoader.do_latest_file_size/1
    (tzdata) lib/tzdata/release_updater.ex:48: Tzdata.ReleaseUpdater.loaded_tzdata_matches_iana_file_size?/0
    (tzdata) lib/tzdata/release_updater.ex:36: Tzdata.ReleaseUpdater.poll_for_update/0
    (tzdata) lib/tzdata/release_updater.ex:17: Tzdata.ReleaseUpdater.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :check_if_time_to_update
State: []
```

Thank you

**Comment by adrianotadao** [comment]
Sorry, I needed to change my `mix.exs` to use specific versions of libs.

**Comment by smeevil** [comment]
Np, glad you resolved it :)
